### PR TITLE
Feat/update angular 14

### LINKED ISSUE #133: Support Angular 14
I tested angular under 14 and everything works, so I think it would be enough to just update the peer dependencies.

### PR DESCRIPTION
**Pull request by fhemery**
This includes both the upgrade to angular 14 and the upgrade to socket io 4.5.1 (latest), which fixes a critical vulnerability.

Tested by building locally the library and linking to this lib on one of my personal projects.

Closes #133

### CODE REVIEW

**Review by Helveg — APPROVED** [review]
Looks good! Thanks for the contribution!

**Comment by Helveg** [comment]
@rodgc probably requires a new release?

**Comment by Karman40** [comment]
@Helveg Yes, it would be necessary.

**Comment by RRGT19** [comment]
Any update on this new release?

**Comment by Helveg** [comment]
Ping @rodgc

**Pull request merged**
