### PR TITLE
chore(packages) update packages to angular 13

### LINKED ISSUE #118: Bump version to Angular v13.x.x
Version 13.x.x of Angular is released but `ngx-socket-io` still depends on 12.x.x.x which is why I cannot use it in my project right now. A `--force` does the job without breaking anything but it always give me a high pulse everytime I use it :fearful: 
```
> $ npm i ngx-socket-io           
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: xxx@0.0.0
npm ERR! Found: @angular/common@13.0.2
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"~13.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^12.0.0" from ngx-socket-io@4.1.0
npm ERR! node_modules/ngx-socket-io
npm ERR!   ngx-socket-io@"*" from the root project
```

Would be awesome if you could bump that dependency if it does not break everything.

### PR DESCRIPTION
**Pull request by heuristicAL**
Updates angular packages to v13 and bumps any relevant packages (like `ng-packagr`). Fixes #118 

I didn't bother updating `socket-io` and `socket-io-client` as #108 already has that goal.

### CODE REVIEW

**Comment by EverettZ** [comment]
bump?

**Comment by sucotronic** [comment]
This will need a new release with MAJOR number change.

**Comment by nelson777** [comment]
So... this means we'll a new release soon ?

**Comment by sucotronic** [comment]
Yeah! Let me do some local testing to verify it all works and we'll do a v5.0.0 release ;)

**Pull request merged**
