### PR TITLE
Docs Update. Prettier, Husky Added

### PR DESCRIPTION
**Pull request by InSantoshMahto**
1. created  .editorconfig file
2. created .prettierrc file
3. update app version 4.0.1
4. add pre commit hooks using husky
5. updated docs link for option key

### CODE REVIEW

**Comment by InSantoshMahto** [comment]
> 1. created  .editorconfig file
> 2. created .prettierrc file
> 3. update app version 4.0.1
> 4. add pre commit hooks using husky
> 5. updated docs link for option key

Documentation Needed for SocketIoConfig Options

**Review by Helveg — COMMENTED** [review]
Thanks for this contribution! Could you explain the changes in `src/socket-io.service.ts`? It looks like formatting only changes, is this correct?

**Comment by InSantoshMahto** [comment]
Yes. in this PR `src/socket-io.service.ts` only formatting was made.
i have a plan to work on several issue and improvement.

**Comment by InSantoshMahto** [comment]
I think i address this issue can you close this [Issue](https://github.com/rodgc/ngx-socket-io/issues/93)

**Pull request merged**
